name: Ruby Warrior CI
on:
  push:
    branches:
      - 'master'
  pull_request:
    branches:
      - '*'
jobs:
  test:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        ruby:
          - '3.3'
          - '3.2'
          - '3.1'
          - '3.0'
          - '2.7'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - run: bundle exec rake
